### ISSUE TITLE
Add WordLookup Instant Dictionary?

### ISSUE THREAD

**Issue by john-chase** [Priyank-Vaghela/Awesome-Bookmarklets#1]
Pull request submitted. Repo here: https://github.com/john-chase/projects_mashups_word-lookup-bookmarklet/tree/barDisplay
Thanks in advance for the consideration!
Super nice list...

**Comment by priyank-vaghela** [comment]
Good concept. I tried the [bookmarklet](https://github.com/john-chase/projects_mashups_word-lookup-bookmarklet/blob/barDisplay/dist/js/main.js); however, it doesn't seem to work. Please feel free to update your repository's README.md with instructions to use it with instant lookup functionality if I'm missing anything.

I would be happy to include the BKMT further. Thanks for submitting a PR.

**Comment by john-chase** [comment]
Hi Priyank,
Thanks for the quick response. Apologies - I don't mean for you to become
my tester. It's working for me on a Mac in Firefox and Chrome, but not
Safari. Not sure why. Were you also trying in Safari? Haven't tried any
browsers on Windows. Thanks in advance for the help. I will do more
debugging before I resubmit.
Best,
John

**Comment by john-chase** [comment]
Hello Priyank,
This has been updated and I have confirmed with several others that it works (Chrome, Firefox, and Safari): https://github.com/john-chase/projects_mashups_word-lookup-bookmarklet/blob/simplified/dist/js/main.js
Let me know if you have any other problems. Safari had an issue with the lookbehind REGEX construct. Note the branch has changed.
Thanks again,
John

**Comment by priyank-vaghela** [comment]
Hello John, thank you for the clarification and update. I am using Google Chrome for testing, and it worked today without any issue. I have added Word Lookup & Instant Dictionary BKMT to the repository. 

Please feel free to open a new issue/PR for any new BMKT. Thanks for the contribution.

BMKT added. Issue closed.

**Comment by john-chase** [comment]
Awesome! Thanks Priyank, much appreciated.
